# Generated by Django 3.1.4 on 2020-12-16 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0002_ticket_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ip',
            field=models.CharField(max_length=15, verbose_name='IP adress'),
        ),
    ]
